import jsPDF from "jspdf";
import "jspdf-autotable";
import type { Asset, InventoryAudit, Office } from "@/types";

declare module "jspdf" {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => jsPDF;
  }
}

interface AuditReportData {
  audit: InventoryAudit;
  office: Office;
  assets: Asset[];
  generatedBy: string;
  generatedAt: string;
}

export function generateAuditReport(data: AuditReportData): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("Jordan Post - Asset Inventory Audit Report", pageWidth / 2, 15, { align: "center" });

  doc.setFontSize(10);
  doc.text("Jordanian National Postal Service", pageWidth / 2, 22, { align: "center" });
  doc.text("تقرير جرد الأصول - البريد الأردني", pageWidth / 2, 28, { align: "center" });

  // Gold accent bar
  doc.setFillColor(217, 119, 6);
  doc.rect(0, 35, pageWidth, 2, "F");

  // Audit details
  let y = 45;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text(`Session Code: ${data.audit.sessionCode}`, 15, y);
  doc.text(`Date: ${new Date(data.audit.scheduledDate).toLocaleDateString("en-US")}`, 15, y + 7);
  doc.text(`Office: ${data.office.officeCode} - ${data.office.officeName}`, 15, y + 14);
  doc.text(`Status: ${data.audit.status}`, 15, y + 21);

  if (data.office.employee) {
    doc.text(`Assigned Employee: ${data.office.employee.fullName} (#${data.office.employee.employeeNumber})`, 15, y + 28);
  }

  // Summary stats
  y += 38;
  doc.setFillColor(241, 245, 249);
  doc.roundedRect(15, y, pageWidth - 30, 20, 3, 3, "F");

  doc.setFontSize(9);
  doc.text(`Total Items: ${data.audit.totalItems}`, 25, y + 8);
  doc.text(`Variance: ${data.audit.varianceCount}`, 100, y + 8);
  doc.text(`Health Score: ${calculateHealthScore(data.assets)}%`, 170, y + 8);

  const good = data.assets.filter((a) => a.condition === "GOOD").length;
  const maintenance = data.assets.filter((a) => a.condition === "UNDER_MAINTENANCE").length;
  const scrapped = data.assets.filter((a) => a.condition === "SCRAPPED").length;
  doc.text(`Good: ${good}`, 25, y + 15);
  doc.text(`Maintenance: ${maintenance}`, 100, y + 15);
  doc.text(`Scrapped: ${scrapped}`, 170, y + 15);

  // Asset table
  y += 30;
  doc.setFontSize(12);
  doc.text("Asset Inventory List", 15, y);
  y += 5;

  const tableData = data.assets.map((asset) => [
    asset.assetTag,
    asset.serialNumber,
    asset.itemNameAr,
    asset.subCategory,
    asset.condition === "GOOD" ? "جيد" : asset.condition === "UNDER_MAINTENANCE" ? "صيانة" : "مهمل",
    asset.purchasePrice ? `JOD ${asset.purchasePrice.toFixed(2)}` : "-",
  ]);

  doc.autoTable({
    startY: y,
    head: [["Asset Tag", "Serial Number", "Item Name (AR)", "Category", "Condition", "Price (JOD)"]],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: {
      fillColor: [2, 132, 199],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 35 },
      2: { cellWidth: 50 },
      3: { cellWidth: 30 },
      4: { cellWidth: 20 },
      5: { cellWidth: 25 },
    },
    margin: { left: 15, right: 15 },
  });

  // Footer
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable?.finalY ?? y + 50;
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by: ${data.generatedBy}`, 15, finalY + 15);
  doc.text(`Generated at: ${data.generatedAt}`, 15, finalY + 20);
  doc.text("Jordan Post - Royal Mail Service | official Jordanian Government Entity", pageWidth / 2, finalY + 25, { align: "center" });

  return doc;
}

function calculateHealthScore(assets: Asset[]): number {
  if (assets.length === 0) return 0;
  const good = assets.filter((a) => a.condition === "GOOD").length;
  return Math.round((good / assets.length) * 100);
}
